<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/2_Valores_Nulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**VALORES NULOS**

In [14]:
#Cargar archivo csv desde COLAB
#from google.colab import files
#files.upload()

In [2]:
#Carga desde un archivo .xlsx sin indice
data = pd.read_excel('Análisis_de_Piso_2.xlsx')
data.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Factor minimo mejor vendedor,Factor minimo mejor vendedor .1,Unnamed: 12,Unnamed: 13
0,Leads Prom X Mes,T. Ventas Piso,Factor,Total de Ventas Historicas,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,0,1,23,0,1,5,1,0,1.00,5.00,1,20
3,10,11,0.18,18,6,0.61,59,40,0.31,0.02,3.28,2.22,7,10
4,0,0,0,NaN,0,0,1,1,0,0,0.00,0.00,NaN,NaN

In [3]:
#Eliminar primera fila o filas innecesarias
data1= pd.read_excel('Análisis_de_Piso_2.xlsx', skiprows=1)
data1

,Leads Prom X Mes,T. Ventas Piso,Factor,Total de Ventas Historicas,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.00,1.0,23,0.00,1.0,5.0,1.00,0.00,1.00,5.00,1.0,20.0
2,10.0,11.0,0.18,18.0,6,0.61,59.0,40.0,0.31,0.02,3.28,2.22,7.0,10.0
3,0.0,0.0,0.00,NaN,0,0.00,1.0,1.0,0.00,0.00,0.00,0.00,NaN,NaN
4,8.0,3.0,0.09,8.0,11,0.38,28.0,31.0,0.29,0.01,3.50,3.88,9.0,18.0
5,7.0,9.0,0.16,15.0,8,0.60,64.0,30.0,0.23,0.02,4.27,2.00,13.0,7.0
6,1.0,1.0,0.25,4.0,17,0.25,21.0,26.0,0.19,0.01,5.25,6.50,18.0,23.0
7,16.0,6.0,0.06,NaN,0,0.00,54.0,8.0,0.00,0.00,0.00,0.00,NaN,NaN
8,1.0,0.0,0.00,NaN,0,0.00,3.0,5.0,0.00,0.00,0.00,0.00,NaN,NaN
9,2.0,0.0,0.00,2.0,19,0.00,25.0,22.0,0.08,0.00,12.50,11.00,22.0,26.0
10,2.0,2.0,0.15,21.0,4,0.10,20.0,32.0,1.05,0.00,0.95,1.52,NaN,3.0
11,8.0,5.0,0.11,12.0,9,0.42,36.0,25.0,0.33,0.02,3.00,2.08,6.0,9.0
12,6.0,0.0,0.00,1.0,23,0.00,19.0,5.0,0.05,0.00,19.00,5.00,23.0,20.0
13,3.0,5.0,0.56,NaN,-,0.00,7.0,5.0,0.00,0.00,0.00,0.00,NaN,NaN
14,4.0,0.0,0.00,NaN,-,0.00,8.0,7.0,0.00,0.00,0.00,0.00,NaN,NaN
15,1.0,0.0,0.00,2.0,19,0.00,25.0,22.0,0.08,0.00,12.50,11.00,22.0,26.0
16,3.0,0.0,0.00,11.0,10,0.00,17.0,11.0,0.65,0.00,1.55,1.00,3.0,1.0
17,9.0,7.0,0.11,25.0,3,0.28,34.0,61.0,0.74,0.00,1.36,2.44,2.0,12.0
18,0.0,2.0,0.02,2.0,19,1.00,18.0,6.0,0.11,0.17,9.00,3.00,20.0,15.0
19,8.0,1.0,0.13,1.0,23,1.00,5.0,2.0,0.20,0.50,5.00,2.00,17.0,7.0
20,2.0,0.0,0.00,NaN,-,0.00,4.0,8.0,0.00,0.00,0.00,0.00,NaN,NaN
21,0.0,2.0,1.00,3.0,18,0.67,1.0,5.0,3.00,0.13,0.33,1.67,NaN,4.0
22,0.0,0.0,0.00,NaN,-,0.00,0.0,7.0,0.00,0.00,0.00,0.00,NaN,NaN
23,7.0,6.0,0.12,16.0,7,0.38,48.0,49.0,0.33,0.01,3.00,3.06,6.0,16.0
24,1.0,0.0,0.00,NaN,-,0.00,3.0,2.0,0.00,0.00,0.00,0.00,NaN,NaN
25,0.0,0.0,0.00,NaN,-,0.00,4.0,3.0,0.00,0.00,0.00,0.00,NaN,NaN
26,2.0,0.0,0.00,NaN,-,0.00,3.0,5.0,0.00,0.00,0.00,0.00,NaN,NaN
27,0.0,1.0,0.02,2.0,19,0.50,9.0,4.0,0.22,0.13,4.50,2.00,14.0,7.0
28,9.0,3.0,0.11,7.0,13,0.43,35.0,24.0,0.20,0.02,5.00,3.43,17.0,17.0
29,6.0,4.0,0.18,8.0,11,0.50,29.0,42.0,0.28,0.01,3.63,5.25,10.0,21.0
30,17.0,18.0,0.09,28.0,2,0.64,117.0,66.0,0.24,0.01,4.18,2.36,12.0,11.0
31,4.0,1.0,0.06,NaN,-,0.00,22.0,9.0,0.00,0.00,0.00,0.00,NaN,NaN
32,4.0,0.0,0.00,6.0,14,0.00,48.0,55.0,0.13,0.00,8.00,9.17,19.0,24.0
33,0.0,0.0,0.00,1.0,23,0.00,4.0,3.0,0.25,0.00,4.00,3.00,11.0,15.0
34,3.0,0.0,0.00,6.0,14,0.00,29.0,36.0,0.21,0.00,4.83,6.00,15.0,22.0
35,0.0,5.0,1.00,6.0,14,0.83,5.0,9.0,1.20,0.09,0.83,1.50,NaN,2.0
36,6.0,0.0,0.00,NaN,-,0.00,1.0,6.0,0.00,0.00,0.00,0.00,NaN,NaN
37,10.0,14.0,0.11,36.0,1,0.39,123.0,75.0,0.29,0.01,3.42,2.08,8.0,9.0
38,3.0,0.0,0.00,NaN,-,0.00,3.0,2.0,0.00,0.00,0.00,0.00,NaN,NaN
39,1.0,0.0,0.00,NaN,-,0.00,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN
40,3.0,3.0,0.11,21.0,4,0.14,46.0,57.0,0.46,0.00,2.19,2.71,4.0,13.0
41,NaN,NaN,NaN,263.0,NaN,NaN,979.0,811.0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Identificar valores nulos por columna
valores_nulos=data1.isnull().sum()
valores_nulos

Leads Prom X Mes                2
T. Ventas Piso                  2
Factor                          2
Total de Ventas Historicas     15
RAKING VENTAS                   2
Dependencia de Piso             2
Historico de PDM                1
Historico de SDC                2
Conversion PDM                  3
Conversion SDC                  3
Factor  PDM                     2
Factor  SDC                     2
Raking PDM                     19
Raking SDC                     16
dtype: int64

In [5]:
#Identificar valores nulos por dataframe
valores_nulos=data1.isnull().sum().sum()
valores_nulos

np.int64(73)

**Métodos de Sustitución de Valores Nulos**

In [ ]:
#empezamos con "lead prom x mes" con .fillna para llenar con un valor especifico, en este caso "0" ya que representa ninguna venta
data1["Leads Prom X Mes"] =data1["Leads Prom X Mes"].fillna("0")

In [7]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Leads Prom X Mes                0
T. Ventas Piso                  2
Factor                          2
Total de Ventas Historicas     15
RAKING VENTAS                   2
Dependencia de Piso             2
Historico de PDM                1
Historico de SDC                2
Conversion PDM                  3
Conversion SDC                  3
Factor  PDM                     2
Factor  SDC                     2
Raking PDM                     19
Raking SDC                     16
dtype: int64

In [ ]:
#volvemos a ultilizar .fillna para llenar con un valor especifico, en este caso "0" ya que representa ninguna venta en piso
data1["T. Ventas Piso "] =data1["T. Ventas Piso "].fillna("0")

In [9]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Leads Prom X Mes                0
T. Ventas Piso                  0
Factor                          2
Total de Ventas Historicas     15
RAKING VENTAS                   2
Dependencia de Piso             2
Historico de PDM                1
Historico de SDC                2
Conversion PDM                  3
Conversion SDC                  3
Factor  PDM                     2
Factor  SDC                     2
Raking PDM                     19
Raking SDC                     16
dtype: int64

In [ ]:
#sustituimos nuevamente con 0 porque no aplica a los asesores que no tienen ventas en piso, de esta manera podemos identificar los valores nulos y no perder información
data1["Factor   "] =data1["Factor   "].fillna("0")

In [15]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Leads Prom X Mes                0
T. Ventas Piso                  0
Factor                          0
Total de Ventas Historicas     15
RAKING VENTAS                   2
Dependencia de Piso             2
Historico de PDM                1
Historico de SDC                2
Conversion PDM                  3
Conversion SDC                  3
Factor  PDM                     2
Factor  SDC                     2
Raking PDM                     19
Raking SDC                     16
dtype: int64

In [16]:
data1["Total de Ventas Historicas "] =data1["Total de Ventas Historicas "].fillna("0")

In [17]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Leads Prom X Mes                0
T. Ventas Piso                  0
Factor                          0
Total de Ventas Historicas      0
RAKING VENTAS                   2
Dependencia de Piso             2
Historico de PDM                1
Historico de SDC                2
Conversion PDM                  3
Conversion SDC                  3
Factor  PDM                     2
Factor  SDC                     2
Raking PDM                     19
Raking SDC                     16
dtype: int64

In [ ]:
#sustituimos con 0 para las columnas de ventas historicas, raking ventas, dependencia de piso, historico de PDM, historico de SDC, factor PDM, factor SDC, raking PDM, raking SDC, conversion PDM y conversion SDC porque no aplica a los asesores que no tienen ventas en piso, de esta manera podemos identificar los valores nulos y no perder información
data1[["Total de Ventas Historicas ","RAKING VENTAS","Dependencia de Piso ","Historico de PDM","Historico de SDC","Factor  PDM","Factor  SDC","Raking PDM","Raking SDC","Conversion PDM","Conversion SDC"]] =data1[["Total de Ventas Historicas ","RAKING VENTAS","Dependencia de Piso ","Historico de PDM","Historico de SDC","Factor  PDM","Factor  SDC","Raking PDM","Raking SDC","Conversion PDM","Conversion SDC"]].fillna("0")

In [22]:
#corroborar valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

Leads Prom X Mes               0
T. Ventas Piso                 0
Factor                         0
Total de Ventas Historicas     0
RAKING VENTAS                  0
Dependencia de Piso            0
Historico de PDM               0
Historico de SDC               0
Conversion PDM                 0
Conversion SDC                 0
Factor  PDM                    0
Factor  SDC                    0
Raking PDM                     0
Raking SDC                     0
dtype: int64

**Comparamos DataFrame3(Sustitución) y Dataframe4(Eliminación)**

In [24]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Leads Prom X Mes             42 non-null     object
 1   T. Ventas Piso               42 non-null     object
 2   Factor                       42 non-null     object
 3   Total de Ventas Historicas   42 non-null     object
 4   RAKING VENTAS                42 non-null     object
 5   Dependencia de Piso          42 non-null     object
 6   Historico de PDM             42 non-null     object
 7   Historico de SDC             42 non-null     object
 8   Conversion PDM               42 non-null     object
 9   Conversion SDC               42 non-null     object
 10  Factor  PDM                  42 non-null     object
 11  Factor  SDC                  42 non-null     object
 12  Raking PDM                   42 non-null     object
 13  Raking SDC                   42 non-null     object
dtypes: object(14)
memory usage: 4.7+ KB

**Convertir DataSet sin valores nulos a CSV**

In [25]:
#Convertir DataFrame a CSV
data1.to_csv("Análisis_de_Piso_2_Sin_Nulos.csv", index=False)

In [ ]:
#descargar archivo filtrado en csv
#from google.colab import files 
  
  
#files.download("inmuebles_sin_nulos.csv")